#!/usr/bin/env bash
# compose-init.sh — one-time secret generation for docker-compose.full.yml.
# Container analog of nexus-ami/scripts/first-boot-secrets.sh: generates the
# shared secrets every service must agree on ([MUST MATCH] in .env.example)
# and writes them to deploy/docker/.env.compose (gitignored, mode 0600).
#
# Idempotent: refuses to overwrite an existing env file — regenerating would
# invalidate encrypted DB rows (CREDENTIAL_ENCRYPTION_KEY), already-issued
# admin keys (ADMIN_KEY_HMAC_SECRET), and inter-service auth
# (INTERNAL_SERVICE_TOKEN). Delete the file AND the volumes to start over:
#   docker compose -f docker-compose.full.yml down -v
#   rm deploy/docker/.env.compose

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/deploy/docker/.env.compose"

if [ -f "$ENV_FILE" ]; then
  echo "compose-init: $ENV_FILE already exists — keeping it (see header for why)."
  exit 0
fi

mkdir -p "$(dirname "$ENV_FILE")"
umask 177

cat > "$ENV_FILE" <<EOF
# Generated by scripts/compose-init.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) — DO NOT COMMIT.
# Shared-secret contract: see .env.example ([MUST MATCH] tags) and
# nexus-ami/scripts/first-boot-secrets.sh for the per-service consumers.

POSTGRES_PASSWORD=$(openssl rand -hex 24)
INTERNAL_SERVICE_TOKEN=$(openssl rand -hex 32)
HUB_CONFIG_TOKEN=$(openssl rand -hex 32)
ADMIN_KEY_HMAC_SECRET=$(openssl rand -hex 32)
CREDENTIAL_ENCRYPTION_KEY=$(openssl rand -hex 32)
COMPLIANCE_PROXY_API_TOKEN=$(openssl rand -hex 32)
AI_GATEWAY_API_TOKEN=$(openssl rand -hex 32)

# Image coordinates — override to pin a published tag.
NEXUS_IMAGE_REGISTRY=alphabitcore
NEXUS_IMAGE_TAG=latest

# OIDC issuer must match the URL you open the console on.
AUTH_SERVER_ISSUER=https://localhost
EOF

echo "compose-init: wrote $ENV_FILE"
echo "Next: docker compose -f docker-compose.full.yml --env-file deploy/docker/.env.compose up -d"
